print("Hello, World!")
print("This is a test script.")
print("Let's see if it works.")
print("Lorem ipsum dolor sit amet, consectetur adipiscing elit.")
print("Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.")
print("Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.")    
